name: video_launcher_example
description: Fullscreen video launcher
version: 0.2.0
author : Erick Ghaumez <rx.devlabz@gmail.com>

flutter:
  plugin:
    androidPackage: bz.rxla.video_launcher
    pluginClass: VideoLauncherPlugin

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true