name: video_launcher
description: Fullscreen video launcher plugin
version: 0.2.1
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/flutter_video_launcher

flutter:
  plugin:
    androidPackage: bz.rxla.video_launcher
    pluginClass: VideoLauncherPlugin

dependencies:
  flutter: ">=0.0.20 <0.1.0"
